{% set name = "django-cleanup" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bb9fb560aaf62959c81e31fa40885c36bbd5854d5aa21b90df2c7e4ba633531e

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - django_cleanup

about:
  home: https://github.com/un1t/django-cleanup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Deletes old files in Django Apps

extra:
  recipe-maintainers:
    - tschoonj
